//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeronaves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aeronaves()
        {
            this.Comunicaciones = new HashSet<Comunicaciones>();
            this.ComunicacionesControladorAeronave = new HashSet<ComunicacionesControladorAeronave>();
            this.SecuenciaAterrizaje = new HashSet<SecuenciaAterrizaje>();
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int IdAeronave { get; set; }
        public string Modelo { get; set; }
        public string Fabricante { get; set; }
        public int AnioFabricacion { get; set; }
        public string Rutaimagen { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> CapacidadPasajeros { get; set; }
        public Nullable<decimal> CapacidadCarga { get; set; }
        public Nullable<System.DateTime> FechaUltimoMantenimiento { get; set; }
        public string TipoMotor { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public decimal Envergadura { get; set; }
        public decimal Altura { get; set; }
        public int IdEstadoAeronave { get; set; }
        public int CapacidadCombustible { get; set; }
        public Nullable<decimal> Alcance { get; set; }
        public Nullable<int> VelocidadMaxima { get; set; }
        public Nullable<int> AltitudMaxima { get; set; }
        public Nullable<decimal> PesoMaximoDespegue { get; set; }
        public Nullable<int> NumeroMotores { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdAerolinea { get; set; }
    
        public virtual Aerolineas Aerolineas { get; set; }
        public virtual EstadoAeronave EstadoAeronave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comunicaciones> Comunicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicacionesControladorAeronave> ComunicacionesControladorAeronave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecuenciaAterrizaje> SecuenciaAterrizaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
