//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeropuertos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aeropuertos()
        {
            this.Controladores = new HashSet<Controladores>();
            this.Escalas = new HashSet<Escalas>();
            this.Pistas = new HashSet<Pistas>();
            this.PuertasEmbarqueDesembarque = new HashSet<PuertasEmbarqueDesembarque>();
            this.Taxiways = new HashSet<Taxiways>();
        }
    
        public int IdAeropuerto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CiudadID { get; set; }
        public string Pais { get; set; }
        public string CodigoIATA { get; set; }
        public string CodigoICAO { get; set; }
        public Nullable<int> CapacidadAviones { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string ZonaHoraria { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Controladores> Controladores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Escalas> Escalas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pistas> Pistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuertasEmbarqueDesembarque> PuertasEmbarqueDesembarque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taxiways> Taxiways { get; set; }
    }
}
