//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Aproximaciones
    {
        public int IdAproximacion { get; set; }
        public Nullable<int> IdVuelo { get; set; }
        public Nullable<System.DateTime> HoraRegistro { get; set; }
        public Nullable<int> IdInformacionMetereologica { get; set; }
        public Nullable<decimal> DistanciaRestante { get; set; }
        public Nullable<decimal> AnguloDescenso { get; set; }
        public Nullable<int> IdTipoAproximacion { get; set; }
        public Nullable<int> Idestadoaproximacion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> PermisoSobrevuelo { get; set; }
        public Nullable<int> idemergencia { get; set; }
        [JsonIgnore]
        public virtual Emergencias Emergencias { get; set; }
        [JsonIgnore]
        public virtual EstadoAproximacion EstadoAproximacion { get; set; }
        [JsonIgnore]
        public virtual InformacionMeteorologica InformacionMeteorologica { get; set; }
        [JsonIgnore]
        public virtual TipoAproximacion TipoAproximacion { get; set; }
            [JsonIgnore]
         public virtual Vuelos Vuelos { get; set; }
    }
}
