//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        public int IdAsiento { get; set; }
        public Nullable<int> NúmeroAsiento { get; set; }
        public string Clase { get; set; }
        public string Disponibilidad { get; set; }
        public Nullable<int> IDNumeroVuelo { get; set; }
    
        public virtual Vuelos Vuelos { get; set; }
    }
}
