//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aterrizajes
    {
        public int IdAterrizaje { get; set; }
        public Nullable<int> IdDatosMinimos { get; set; }
        public Nullable<int> IdEstadoPista { get; set; }
        public Nullable<int> IdInformacionMetereologica { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<int> IdVuelo { get; set; }
        public Nullable<int> idemergencia { get; set; }
        public Nullable<bool> PermisoAterrizaje { get; set; }
    
        public virtual DatosMinimosAterrizaje DatosMinimosAterrizaje { get; set; }
        public virtual Emergencias Emergencias { get; set; }
        public virtual EstadoPista EstadoPista { get; set; }
        public virtual InformacionMeteorologica InformacionMeteorologica { get; set; }
        public virtual PrioridadesAterrizajes PrioridadesAterrizajes { get; set; }
        public virtual PrioridadesVuelos PrioridadesVuelos { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
