//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aterrizajes
    {
        public int IdAterrizaje { get; set; }
        public Nullable<int> IdDatosMinimos { get; set; }
        public Nullable<int> IdEstadoPista { get; set; }
        public Nullable<int> idemergencia { get; set; }
        public string IDSecuencia { get; set; }
        public Nullable<bool> PermisoAterrizaje { get; set; }
    
        public virtual DatosMinimosAterrizaje DatosMinimosAterrizaje { get; set; }
        public virtual Emergencias Emergencias { get; set; }
        public virtual EstadoPista EstadoPista { get; set; }
        public virtual SecuenciaAterrizaje SecuenciaAterrizaje { get; set; }
    }
}
