//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoridades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autoridades()
        {
            this.ComunicacionesControladorAutoridad = new HashSet<ComunicacionesControladorAutoridad>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TipoAutoridad { get; set; }
        public string Cargo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicacionesControladorAutoridad> ComunicacionesControladorAutoridad { get; set; }
    }
}
