//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoridades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autoridades()
        {
            this.ComunicacionesControladorAutoridad = new HashSet<ComunicacionesControladorAutoridad>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TipoAutoridad { get; set; }
        public string Cargo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicacionesControladorAutoridad> ComunicacionesControladorAutoridad { get; set; }
    }
}
