//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunicaciones()
        {
            this.RegistroComunicaciones = new HashSet<RegistroComunicaciones>();
        }
    
        public int IdComunicacion { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> IdAeronave { get; set; }
        public Nullable<int> IdControlador { get; set; }
        public string ContenidoMensaje { get; set; }
    
        public virtual Aeronaves Aeronaves { get; set; }
        public virtual Controladores Controladores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroComunicaciones> RegistroComunicaciones { get; set; }
    }
}
