//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComunicacionesControladorAeronave
    {
        public int ID { get; set; }
        public Nullable<int> ControladorID { get; set; }
        public Nullable<int> IdAeronave { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Aeronaves Aeronaves { get; set; }
        public virtual Controladores Controladores { get; set; }
    }
}
