//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunicaciones()
        {
            this.RegistroComunicaciones = new HashSet<RegistroComunicaciones>();
        }
    
        public int IdComunicacion { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> IdAeronave { get; set; }
        public Nullable<int> IdControlador { get; set; }
        public string ContenidoMensaje { get; set; }
    
        public virtual Aeronaves Aeronaves { get; set; }
        public virtual Controladores Controladores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroComunicaciones> RegistroComunicaciones { get; set; }
    }
}
