//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controladores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Controladores()
        {
            this.Comunicaciones = new HashSet<Comunicaciones>();
            this.ComunicacionesControladorAeronave = new HashSet<ComunicacionesControladorAeronave>();
            this.ComunicacionesControladorAutoridad = new HashSet<ComunicacionesControladorAutoridad>();
        }
    
        public int ID { get; set; }
        public string IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string TipoControlador { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> IdAeropuerto { get; set; }
        public Nullable<System.DateTime> FechaContratacion { get; set; }
        public string NivelCertificacion { get; set; }
        public string HorarioTrabajo { get; set; }
        public Nullable<decimal> Salario { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comunicaciones> Comunicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicacionesControladorAeronave> ComunicacionesControladorAeronave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComunicacionesControladorAutoridad> ComunicacionesControladorAutoridad { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
