//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosMinimosAterrizaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosMinimosAterrizaje()
        {
            this.Aterrizajes = new HashSet<Aterrizajes>();
        }
    
        public int IdDatosMinimos { get; set; }
        public Nullable<decimal> VelocidadMinima { get; set; }
        public Nullable<decimal> AltitudMinima { get; set; }
        public Nullable<decimal> CombustibleMinimo { get; set; }
        public Nullable<decimal> AnguloDescensoMinimo { get; set; }
        public Nullable<bool> PermisoTorreAproximaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizajes> Aterrizajes { get; set; }
    }
}
