//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desembarques
    {
        public int Id { get; set; }
        public int Puerta_embarque_id { get; set; }
        public int VueloID { get; set; }
        public System.DateTime Hora_inicio { get; set; }
        public System.DateTime Hora_fin { get; set; }
    
        public virtual PuertasEmbarqueDesembarque PuertasEmbarqueDesembarque { get; set; }
    }
}
