//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desembarques
    {
        public int Id { get; set; }
        public int Puerta_embarque_id { get; set; }
        public int VueloID { get; set; }
        public System.DateTime Hora_inicio { get; set; }
        public System.DateTime Hora_fin { get; set; }
    
        public virtual PuertasEmbarqueDesembarque PuertasEmbarqueDesembarque { get; set; }
    }
}
