//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergencias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emergencias()
        {
            this.Aproximaciones = new HashSet<Aproximaciones>();
            this.Aterrizajes = new HashSet<Aterrizajes>();
        }
    
        public int IdEmergencia { get; set; }
        public Nullable<System.DateTime> FechaHoraInicio { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public Nullable<int> idTipoProcedimiento { get; set; }
        public Nullable<int> idvuelo { get; set; }
        public Nullable<int> idaltitudemergencia { get; set; }
        public string idprioridadaterrizaje { get; set; }
        public string DescripcionReportada { get; set; }
        public Nullable<int> IDUsuario { get; set; }
    
        public virtual AltitudEmergencia AltitudEmergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aproximaciones> Aproximaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizajes> Aterrizajes { get; set; }
        public virtual PrioridadesAterrizajes PrioridadesAterrizajes { get; set; }
        public virtual Procedimientos Procedimientos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
