//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposEmergencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquiposEmergencia()
        {
            this.Procedimientos = new HashSet<Procedimientos>();
        }
    
        public int IdEquipoEmergencia { get; set; }
        public Nullable<int> IdTipoEmergencia { get; set; }
        public string NombreEquipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual TipoEmergencia TipoEmergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedimientos> Procedimientos { get; set; }
    }
}
