//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipaje
    {
        public int IdEquipaje { get; set; }
        public Nullable<int> NúmeroMaletas { get; set; }
        public Nullable<decimal> PesoTotal { get; set; }
        public Nullable<int> IDPasajero { get; set; }
    
        public virtual Pasajeros Pasajeros { get; set; }
    }
}
