//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipaje
    {
        public int IdEquipaje { get; set; }
        public Nullable<int> NúmeroMaletas { get; set; }
        public Nullable<decimal> PesoTotal { get; set; }
        public Nullable<int> IDPasajero { get; set; }
    
        public virtual Pasajeros Pasajeros { get; set; }
    }
}
