//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoPista()
        {
            this.Aterrizajes = new HashSet<Aterrizajes>();
        }
    
        public int IdEstadoPista { get; set; }
        public Nullable<int> IdPista { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizajes> Aterrizajes { get; set; }
        public virtual Pistas Pistas { get; set; }
    }
}
