//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoPista()
        {
            this.Aterrizajes = new HashSet<Aterrizajes>();
        }
    
        public int IdEstadoPista { get; set; }
        public Nullable<int> IdPista { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> UltimaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizajes> Aterrizajes { get; set; }
        public virtual Pistas Pistas { get; set; }
    }
}
