//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosDespegue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventosDespegue()
        {
            this.ReporteFinalDespegues = new HashSet<ReporteFinalDespegues>();
        }
    
        public int ID { get; set; }
        public int IdVuelo { get; set; }
        public string TipoEvento { get; set; }
        public string Descripcion { get; set; }
        public string FechaHora { get; set; }
        public string Estado { get; set; }
    
        public virtual Vuelos Vuelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteFinalDespegues> ReporteFinalDespegues { get; set; }
    }
}
