//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialVuelos
    {
        public int IdHistorialVuelo { get; set; }
        public Nullable<System.DateTime> FechaHoraSalida { get; set; }
        public Nullable<System.DateTime> FechaHoraLlegada { get; set; }
        public string EstadoVuelo { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> IDNumeroVuelo { get; set; }
    
        public virtual Vuelos Vuelos { get; set; }
    }
}
