//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstruccionesRodaje
    {
        public int Id { get; set; }
        public int Operacion_rodaje_id { get; set; }
        public string Instruccion { get; set; }
    
        public virtual OperacionesRodaje OperacionesRodaje { get; set; }
    }
}
