//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperacionesRodaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperacionesRodaje()
        {
            this.InstruccionesRodaje = new HashSet<InstruccionesRodaje>();
        }
    
        public int Id { get; set; }
        public int IdVuelo { get; set; }
        public int PistaId { get; set; }
        public int TaxiwayId { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstruccionesRodaje> InstruccionesRodaje { get; set; }
        public virtual Vuelos Vuelos { get; set; }
        public virtual Pistas Pistas { get; set; }
        public virtual Taxiways Taxiways { get; set; }
    }
}
