//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilotos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pilotos()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdAerolinea { get; set; }
        public string Licencia { get; set; }
        public string Cargo { get; set; }
        public string NivelCertificacion { get; set; }
        public string HorarioTrabajo { get; set; }
    
        public virtual Aerolineas Aerolineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
    }
}
