//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pistas()
        {
            this.AsignacionPistasDespegue = new HashSet<AsignacionPistasDespegue>();
            this.EstadoPista = new HashSet<EstadoPista>();
            this.OperacionesRodaje = new HashSet<OperacionesRodaje>();
            this.ReporteFinalDespegues = new HashSet<ReporteFinalDespegues>();
        }
    
        public int IdPista { get; set; }
        public Nullable<int> IdAeropuerto { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public string Designacion { get; set; }
        public string Superficie { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionPistasDespegue> AsignacionPistasDespegue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoPista> EstadoPista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesRodaje> OperacionesRodaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteFinalDespegues> ReporteFinalDespegues { get; set; }
    }
}
