//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosicionesEstacionamiento
    {
        public int Id { get; set; }
        public int VueloID { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public string Restricciones { get; set; }
    
        public virtual Vuelos Vuelos { get; set; }
    }
}
