//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posiciones
    {
        public int IdPosicion { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<int> Altitud { get; set; }
        public Nullable<int> Velocidad { get; set; }
        public Nullable<int> Rumbo { get; set; }
        public Nullable<int> IdNumeroVuelo { get; set; }
    
        public virtual Vuelos Vuelos { get; set; }
    }
}
