//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posiciones
    {
        public int IdPosicion { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<int> Altitud { get; set; }
        public Nullable<int> Velocidad { get; set; }
        public Nullable<int> Rumbo { get; set; }
        public Nullable<int> IdNumeroVuelo { get; set; }
    
        public virtual Vuelos Vuelos { get; set; }
    }
}
