//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedimientos
    {
        public int IdProcedimiento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Pasos { get; set; }
        public string EquipoNecesario { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdEquipoEmergencia { get; set; }
    
        public virtual EquiposEmergencia EquiposEmergencia { get; set; }
    }
}
