//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuertasEmbarqueDesembarque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuertasEmbarqueDesembarque()
        {
            this.Desembarques = new HashSet<Desembarques>();
            this.Embarques = new HashSet<Embarques>();
        }
    
        public int Id { get; set; }
        public int AeropuertoId { get; set; }
        public string Numero { get; set; }
        public string Ubicacion { get; set; }
        public bool Disponible { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desembarques> Desembarques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Embarques> Embarques { get; set; }
    }
}
