//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroEmergencia
    {
        public int IdRegistroEmergencia { get; set; }
        public Nullable<int> IdEmergencia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Emergencias Emergencias { get; set; }
    }
}
