//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteFinalDespegues
    {
        public int Id { get; set; }
        public int IdVuelo { get; set; }
        public int IdPista { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public int IdInformacionMeteorologica { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Descripcion { get; set; }
        public int IdEventoDespegue { get; set; }
        public int IdRegistroComunicacion { get; set; }
    
        public virtual EventosDespegue EventosDespegue { get; set; }
        public virtual InformacionMeteorologica InformacionMeteorologica { get; set; }
        public virtual Pistas Pistas { get; set; }
        public virtual RegistroComunicaciones RegistroComunicaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
