//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuenciaAterrizaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecuenciaAterrizaje()
        {
            this.Aterrizajes = new HashSet<Aterrizajes>();
        }
    
        public string IDSecuencia { get; set; }
        public int IdAeronave { get; set; }
        public string ETA { get; set; }
        public int IDClima { get; set; }
        public string Instrucciones_especiales { get; set; }
        public string Prioridad { get; set; }
    
        public virtual Aeronaves Aeronaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizajes> Aterrizajes { get; set; }
        public virtual InformacionMeteorologica InformacionMeteorologica { get; set; }
        public virtual PrioridadesAterrizajes PrioridadesAterrizajes { get; set; }
    }
}
