//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuenciaAterrizaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecuenciaAterrizaje()
        {
            this.Aterrizajes = new HashSet<Aterrizajes>();
        }
    
        public string IDSecuencia { get; set; }
        public int IdAeronave { get; set; }
        public string ETA { get; set; }
        public int IDClima { get; set; }
        public string Instrucciones_especiales { get; set; }
        public string Prioridad { get; set; }
    
        public virtual Aeronaves Aeronaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aterrizajes> Aterrizajes { get; set; }
        public virtual InformacionMeteorologica InformacionMeteorologica { get; set; }
        public virtual PrioridadesAterrizajes PrioridadesAterrizajes { get; set; }
    }
}
