//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuenciaAterrizaje
    {
        public string IDSecuencia { get; set; }
        public int IdAeronave { get; set; }
        public string ETA { get; set; }
        public int IDClima { get; set; }
        public string Instrucciones_especiales { get; set; }
        public string Prioridad { get; set; }
    
        public virtual Aeronaves Aeronaves { get; set; }
        public virtual InformacionMeteorologica InformacionMeteorologica { get; set; }
    }
}
