//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxiways
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxiways()
        {
            this.OperacionesRodaje = new HashSet<OperacionesRodaje>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdAeropuerto { get; set; }
        public string Designacion { get; set; }
        public string Tipo { get; set; }
    
        public virtual Aeropuertos Aeropuertos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesRodaje> OperacionesRodaje { get; set; }
    }
}
