//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tripulacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tripulacion()
        {
            this.Aerolineas = new HashSet<Aerolineas>();
        }
    
        public int IdMiembroTripulacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Puesto { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public string Cedula { get; set; }
        public Nullable<System.DateTime> FechaContratacion { get; set; }
        public string ExperienciaLaboral { get; set; }
        public string HistorialVuelos { get; set; }
        public string HorarioTrabajo { get; set; }
        public string Certificaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aerolineas> Aerolineas { get; set; }
    }
}
