//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelos()
        {
            this.Aproximaciones = new HashSet<Aproximaciones>();
            this.Asientos = new HashSet<Asientos>();
            this.AsignacionDespeguesUsuario = new HashSet<AsignacionDespeguesUsuario>();
            this.AsignacionPistasDespegue = new HashSet<AsignacionPistasDespegue>();
            this.Emergencias = new HashSet<Emergencias>();
            this.Escalas = new HashSet<Escalas>();
            this.EventosDespegue = new HashSet<EventosDespegue>();
            this.HistorialVuelos = new HashSet<HistorialVuelos>();
            this.Mercancias = new HashSet<Mercancias>();
            this.OperacionesRodaje = new HashSet<OperacionesRodaje>();
            this.Pasajeros = new HashSet<Pasajeros>();
            this.Posiciones = new HashSet<Posiciones>();
            this.PosicionesEstacionamiento = new HashSet<PosicionesEstacionamiento>();
            this.RegistroComunicaciones = new HashSet<RegistroComunicaciones>();
            this.ReporteFinalDespegues = new HashSet<ReporteFinalDespegues>();
            this.Tripulación = new HashSet<Tripulación>();
        }
    
        public int IdVuelo { get; set; }
        public string NumeroVuelo { get; set; }
        public Nullable<int> IdAerolinea { get; set; }
        public Nullable<int> IDAeronave { get; set; }
        public Nullable<int> IdEstadoVuelo { get; set; }
        public Nullable<int> IdPiloto { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<int> IDTipovuelo { get; set; }
        public Nullable<int> IDOrigen { get; set; }
        public Nullable<int> IDDestino { get; set; }
        public string Ruta { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public Nullable<System.DateTime> HoraLlegada { get; set; }
        public Nullable<int> DuracionEstimada { get; set; }
    
        public virtual Aerolineas Aerolineas { get; set; }
        public virtual Aeronaves Aeronaves { get; set; }
        public virtual Aeropuertos Aeropuertos { get; set; }
        public virtual Aeropuertos Aeropuertos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aproximaciones> Aproximaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asientos> Asientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionDespeguesUsuario> AsignacionDespeguesUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionPistasDespegue> AsignacionPistasDespegue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergencias> Emergencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Escalas> Escalas { get; set; }
        public virtual EstadoVuelo EstadoVuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventosDespegue> EventosDespegue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialVuelos> HistorialVuelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mercancias> Mercancias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesRodaje> OperacionesRodaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasajeros> Pasajeros { get; set; }
        public virtual Pilotos Pilotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posiciones> Posiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosicionesEstacionamiento> PosicionesEstacionamiento { get; set; }
        public virtual PrioridadesVuelos PrioridadesVuelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroComunicaciones> RegistroComunicaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteFinalDespegues> ReporteFinalDespegues { get; set; }
        public virtual TipoVuelo TipoVuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tripulación> Tripulación { get; set; }
    }
}
